language: node_js
node_js:
  - '10.15.0'
script:
  - set -e

  - echo 'Checking for missing change logs...' && echo -en 'travis_fold:start:change\\r'
  - git fetch origin master:refs/remotes/origin/master -a
  - node common/scripts/install-run-rush.js change -v
  - echo -en 'travis_fold:end:change\\r'

  - echo 'Checking for inconsistent dependency versions' && echo -en 'travis_fold:start:check\\r'
  - node common/scripts/install-run-rush.js check
  - echo -en 'travis_fold:end:check\\r'

  - echo 'Installing...' && echo -en 'travis_fold:start:install\\r'
  - node common/scripts/install-run-rush.js install
  - echo -en 'travis_fold:end:install\\r'

  - echo 'Testing...' && echo -en 'travis_fold:start:test\\r'
  - cd libraries/bin-packing
  - npm run test
  -  cd ../../
  - echo -en 'travis_fold:end:test\\r'

  - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
  - node common/scripts/install-run-rush.js rebuild --verbose
  - echo -en 'travis_fold:end:build\\r'
